---
title: "NanoSIMS Data Processing"
author: "A. Pasulka"
date: "`r Sys.Date()`"
output: html_document
---

```{r "load libraries", echo = FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(lans2r)
library(knitr)
opts_chunk$set(dev=c("png", "pdf"), dev.args=list(pdf = list(encoding="WinAnsi", useDingbats=FALSE)),
  fig.keep="all", fig.path = file.path("plot", "NANOSIMS_processing_"))
```

## Load data

```{r}
load(file.path("data", "nanosims_data.RData"))
```

## Derived quantities calculations

```{r}
# calculation function
#source(file.path(root, "scripts", "calculations.R"))

# assuming cirumnatural abundance for unlabeled samples for the purpose 
# of determining fractionation between runs
nat <- list(
  R13C = 0.011237,
  R15N = 0.003677
)

# calculations
nanosims_calculations <-
  nanosims_data %>% 
  # ### 1) consolidate analyses that measured 12C2 and 13C12C instead of 12C and 13C ions
  # # --> since R=13C/12C and 13C12C = 2*13C*12C, 12C2 = 12C*12C 
  # # --> need to divide 13C12C ion count by 2 to ultimately get correct ratio: 
  # # --> 0.5*13C12C/12C2 = 0.5*13C*12C/(12C*12C) = 13C/12C
  # calculate(
  #   data_type = "ion_count", 
  #   c(`12C`, `12C2`), c(`13C`, 0.5*`13C12C`), c(`14N12C`, NA), c(`15N12C`, NA),
  #   value_fun = function(ion1, ion2) ifelse(is.na(ion1), ion2, ion1),
  #   error_fun = function(ion1, ion2) lans2r:::iso.errN(ifelse(is.na(ion1), ion2, ion1)),
  #   name_fun = function(ion1, ...) deparse(substitute(ion1))
  # ) %>% 
  # arrange(analysis, variable, ROI, plane) %>% 
  # # remove the extraneous 12C2 and 13C12C columns
  # filter(variable != "12C2", variable != "13C12C") %>% 

  # ### calculate maximum counts for each ROI (from plane with max. counts in major ion of each element)
  # group_by(analysis, ROI) %>%
  # calculate(
  #   data_type = "max_count",
  #   c(`12C`, `12C`, plane), c(`13C`, `12C`, plane), c(`14N12C`, `14N12C`, plane), c(`15N12C`, `14N12C`, plane),
  #   value_fun = function(ion, ion_to_max, plane) ion[get_max_cts_plane(ion_to_max, plane)],
  #   error_fun = function(ion, ion_to_max, plane) lans2r:::iso.errN(ion[get_max_cts_plane(ion_to_max, plane)]),
  #   name_fun = function(ion, ...) paste0("max plane ", deparse(substitute(ion))),
  #   filter_new = plane == "all" # same (=max) value for all planes, only keep "all" plane
  # ) %>% ungroup() %>%

  # ### calculate sum of top counts for each ROI (from planes within 25% of counts of top counts)
  # group_by(analysis, ROI) %>%
  # calculate(
  #   data_type = "top_count",
  #   c(`12C`, `12C`, plane), c(`13C`, `12C`, plane), c(`14N12C`, `14N12C`, plane), c(`15N12C`, `14N12C`, plane),
  #   value_fun = function(ion, ion_to_max, plane) sum(ion[get_top_cts_planes(ion_to_max, plane, cutoff = 0.9)]),
  #   error_fun = function(ion, ion_to_max, plane) lans2r:::iso.errN(sum(ion[get_top_cts_planes(ion_to_max, plane, cutoff = 0.9)])),
  #   name_fun = function(ion, ...) paste0("top planes ", deparse(substitute(ion))),
  #   filter_new = plane == "all" # same (=max) value for all planes, only keep "all" plane
  # ) %>% ungroup() %>%

  ### focus on the combined planes and max counts only (i.e. the "all" plane records)
  filter(plane == "all") %>%
#!  mutate(variable = ifelse(data_type == "ion_count", paste("all", variable), variable)) %>%
  
  ### calculate fractionation factors for each run
  # calculate overall run-based fractionation factors from total icon counts across all natural abundance ROIs in a run
  group_by(RunDate) %>%
  calculate(
    data_type = "alpha NS/TRUE",
    c("13C", `13C`, `12C`, NaturalC, nat$R13C), c("15N", `15N12C`, `14N12C`, NaturalN, nat$R15N),
    value_fun = function(name, minor, major, is_natural, nat_ratio) {
      if (!any(is_natural == "yes")) return(-1) # can't calculate, no natural abundance measurements
      sum(minor[is_natural == "yes"], na.rm = TRUE)/sum(major[is_natural == "yes"], na.rm = TRUE) * 1/nat_ratio
    },
    error_fun = function(name, minor, major, is_natural, nat_ratio) {
      if (!any(is_natural == "yes")) return(-1) # can't calculate, no natural abundance measurements
      lans2r:::iso.errR(sum(major[is_natural == "yes"], na.rm = TRUE), sum(minor[is_natural == "yes"], na.rm = TRUE))/nat_ratio
    },
    name_fun = function(name, ...) paste0("alpha ", name)
  ) %>% ungroup() %>%

  # fill in the missing fractionation factors with mean and large errors spanning the whole observed range
  group_by(variable) %>% 
  mutate(
    value = ifelse(data_type == "alpha NS/TRUE" & value == -1, (max(value[value!=-1]) + min(value[value!=-1]))/2, value),
    sigma = ifelse(data_type == "alpha NS/TRUE" & sigma == -1, (max(value[value!=-1]) - min(value[value!=-1]))/2, sigma)
  ) %>% ungroup() %>% 
  
  ### calculate ratios without fractionation correction
  calculate(
    data_type = "ratio",
    c("13C/12C", `13C`, `12C`),
    c("15N/14N", `15N12C`, `14N12C`),
    # c("max plane 13C/12C", `max plane 13C`, `max plane 12C`),
    # c("max plane 15N/14N", `max plane 15N12C`, `max plane 14N12C`),
    # c("top planes 13C/12C", `top planes 13C`, `top planes 12C`),
    # c("top planes 15N/14N", `top planes 15N12C`, `top planes 14N12C`),
    value_fun = function(name, minor, major) minor/major,
    error_fun = function(name, minor, major) lans2r:::iso.errR(major, minor),
    name_fun = function(name, ...) return(name)
  ) %>%
  
  ### calculate ratios with fractionation correction (using the above calculated fractionation factors and errors)
  calculate(
    data_type = "corrected ratio",
    c("13C/12C", `13C`, `12C`, `alpha 13C`, `alpha 13C sigma`), 
    c("15N/14N", `15N12C`, `14N12C`, `alpha 15N`, `alpha 15N sigma`),
    # c("max plane 13C/12C", `max plane 13C`, `max plane 12C`, `alpha 13C`, `alpha 13C sigma`), 
    # c("max plane 15N/14N", `max plane 15N12C`, `max plane 14N12C`, `alpha 15N`, `alpha 15N sigma`),
    # c("top planes 13C/12C", `top planes 13C`, `top planes 12C`, `alpha 13C`, `alpha 13C sigma`), 
    # c("top planes 15N/14N", `top planes 15N12C`, `top planes 14N12C`, `alpha 15N`, `alpha 15N sigma`),
    value_fun = function(name, minor, major, alpha, alpha.err) (minor/major)/alpha,
    error_fun = function(name, minor, major, alpha, alpha.err) (minor/major)/alpha * 
      sqrt( lans2r:::iso.relErrR(major, minor)^2 + (alpha.err/alpha)^2 ),
    name_fun = function(name, ...) return(paste(name, "corr"))
  ) %>%
  
  # ratios that are 0 (because no minor isotope ion counts) are not informative and are removed
  filter(!(data_type %in% c("ratio", "corrected ratio") & value == 0)) %>%
  
  ### caculate resulting fractional abundances for both corrected and uncorrected ratios
  calculate(
    data_type = "abundance", 
    c(`13C/12C`, `13C/12C sigma`), c(`13C/12C corr`, `13C/12C corr sigma`),  
    c(`15N/14N`, `15N/14N sigma`), c(`15N/14N corr`, `15N/14N corr sigma`),
    # c(`max plane 13C/12C`, `max plane 13C/12C sigma`), c(`max plane 13C/12C corr`, `max plane 13C/12C corr sigma`),  
    # c(`max plane 15N/14N`, `max plane 15N/14N sigma`), c(`max plane 15N/14N corr`, `max plane 15N/14N corr sigma`),
    # c(`top planes 13C/12C`, `top planes 13C/12C sigma`), c(`top planes 13C/12C corr`, `top planes 13C/12C corr sigma`),  
    # c(`top planes 15N/14N`, `top planes 15N/14N sigma`), c(`top planes 15N/14N corr`, `top planes 15N/14N corr sigma`),
    value_fun = function(ratio, ...) ratio/(1+ratio),
    error_fun = function(ratio, ratio.err) ratio.err/(1+ratio)^2,
    name_fun = function(ratio, ...) sub("(/\\d+\\w)", " F", deparse(substitute(ratio)))
  ) %>%
  
  # ### C and N sums
  # calculate_sums(
  #   c(`all 13C`, `all 12C`), c(`all 15N12C`, `all 14N12C`),
  #   c(`max plane 13C`, `max plane 12C`), c(`max plane 15N12C`, `max plane 14N12C`),
  #   c(`top planes 13C`, `top planes 12C`), c(`top planes 15N12C`, `top planes 14N12C`)
  # ) %>%
  
  # ### C/N ratios for the C and N sums
  # # NOTE: these max and top counts might not be from the same plane so C/N ratios could be tricky!
  # calculate_ratios(
  #   c(`all 13C` + `all 12C`, `all 15N12C` + `all 14N12C`),
  #   c(`max plane 13C` + `max plane 12C`, `max plane 15N12C` + `max plane 14N12C`),
  #   c(`top planes 13C` + `top planes 12C`, `top planes 15N12C` + `top planes 14N12C`),
  #   name_fun = function(num, denom) { # simplify name a little
  #     paste(sub("^`?([^0-9]+)\\s\\d.*$", "\\1", deparse(substitute(num))), "C/N")
  #   }
  # ) %>%
  
  # ### fractionation factors - individual ROI ratio based
  # # these are not actually used for any calculation but just as information for the fractionation factors
  # mutate(
  #   alpha_ns_ea =
  #     ifelse(
  #       grepl("13C/12C$", variable) & NaturalC == "yes", value/nat$R13C,
  #       ifelse(grepl("15N/14N$", variable) & NaturalN == "yes", value/nat$R15N, NA)
  #     ),
  #   alpha_ns_ea.sigma =
  #     ifelse(
  #       grepl("13C/12C$", variable) & NaturalC == "yes", sigma/nat$R13C,
  #       ifelse(grepl("15N/14N$", variable) & NaturalN == "yes", sigma/nat$R15N, NA)
  #     )
  #   ) %>%
  
  identity()

# cache the calculations
save(nanosims_calculations, file = file.path("data", "nanosims_calculations.RData"))
```

#### Cache the data set

```{r "cache planes with calcs"}
# RData file
save(data_with_calcs, file = file.path(root, "cache", "data_with_calcs.RData"))
# and excel
openxlsx::write.xlsx(data_with_calcs, file = file.path(root, "output", "data_with_calcs.xlsx"))
openxlsx::write.xlsx(data_with_calcs %>% spread_data(), file = file.path(root, "output", "data_with_calcs_wide.xlsx"))
```


## Data information

```{r}
#Look at the data spread out differently - info for each ROI
info_2 <- data_with_calcs %>% spread_data()
kable(info_2)
```

```{r, eval=FALSE}
View(info_2)
```

# Plot new calculated data

#### Summary planes

```{r "summary_virus_planes_vs_size", fig.width = 12, fig.height = 8}
#Plotting ratios and corrected ratios
p <- data_with_calcs %>% 
  filter(Organism %in% c("Syn1", "EhV"), data_type %in% c("ratio", "corrected ratio")) %>% 
  ggplot() +
  aes(size, value, color = paste(Organism, RunDate)) + #paste(Organism, Label, Year)) + 
  geom_errorbar(aes(ymin = value - 2*sigma, ymax = value + 2*sigma), colour="black", width = 0) +
  geom_point(size=2) + 
  labs(x = expression("ROI size ["*mu*"m"^2*"]"), y="", 
       title = expression("Viruses ROI summary ratios (2"*sigma*" error bars)"),
       color = "Samples") + 
  facet_wrap(~variable, scales="free", nrow = 3) + 
  theme_bw()
print(p)
```

```{r "summary_host_planes_vs_size", fig.width = 12, fig.height = 8}
#Plotting ratios and corrected ratios
ggplot2::last_plot() %+%
  (data_with_calcs %>% 
  filter(Organism %in% c("Ehux", "WH8101"), data_type %in% c("ratio", "corrected ratio"))) +
  labs(title = expression("Host ROI summary ratios (2"*sigma*" error bars)"))
```


#### Interactive C/N

Closer look at the C/N

```{r "C to N measures vs size", fig.width = 12, fig.height = 8}
library(plotly)
p2 <- p %+% filter(data_with_calcs, Organism == "Syn1", grepl("C/N", variable)) %+% 
  aes(text = paste("ROI:", ROI)) + labs(x = "size", title = "")
class(p2$mapping) <- "uneval"
ggplotly(p2)
```

